[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
amm_proxy = "DZWNFCeULDmofBEEknDbeq4w2J3oxXyvFKW6kG1L5Kt5"

[programs.localnet]
presale-launcher = "DmTYykBGheDKxJN29jSPPieDrQaw2ZKxjgfGpWiJ6Q5Z"

[registry]
url = "https://github.com/raydium-io/raydium-contract-instructions"

[provider]
cluster = "Localnet"
wallet = "/home/skydiver/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 20000
shutdown_wait = 2000
upgradeable = true

[test.validator]
bind_address = "0.0.0.0"
url = "https://solana-devnet.g.alchemy.com/v2/rkwUwG9MyHsSXk77b_vlGJCsTRuW6Bun"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "EoTcMgcDRTJVZDMZWBoU6rhYHZfkNTVEAfz3uUJRcYGj"

[[test.validator.clone]]
address = "HWy1jotHpo6UqeQxx49dpYYdQB8wj9Qk9MdxwjLvDHB8"

[[test.validator.clone]]
address = "3XMrhbv989VxAMi3DErLV9eJht1pHppW5LbKxe9fkEFR"

[[test.validator.clone]]
address = "8QN9yfKqWDoKjvZmqFsgCzAqwZBQuzVVnC388dN5RCPo"
